package com.ak.little.rainbow.theme
import androidx.compose.ui.graphics.Color

val primaryLight = Color(0xFFA40023)
val onPrimaryLight = Color(0xFFFFFFFF)
val primaryContainerLight = Color(0xFFE90036)
val onPrimaryContainerLight = Color(0xFFFFFFFF)
val secondaryLight = Color(0xFFB42533)
val onSecondaryLight = Color(0xFFFFFFFF)
val secondaryContainerLight = Color(0xFFFF7275)
val onSecondaryContainerLight = Color(0xFF2F0004)
val tertiaryLight = Color(0xFF803E00)
val onTertiaryLight = Color(0xFFFFFFFF)
val tertiaryContainerLight = Color(0xFFB75B00)
val onTertiaryContainerLight = Color(0xFFFFFFFF)
val errorLight = Color(0xFFBA1A1A)
val onErrorLight = Color(0xFFFFFFFF)
val errorContainerLight = Color(0xFFFFDAD6)
val onErrorContainerLight = Color(0xFF410002)
val backgroundLight = Color(0xFFFFF8F7)
val onBackgroundLight = Color(0xFF2A1616)
val surfaceLight = Color(0xFFFFF8F7)
val onSurfaceLight = Color(0xFF2A1616)
val surfaceVariantLight = Color(0xFFFFDAD8)
val onSurfaceVariantLight = Color(0xFF5F3E3E)
val outlineLight = Color(0xFF936E6D)
val outlineVariantLight = Color(0xFFE9BCBA)
val scrimLight = Color(0xFF000000)
val inverseSurfaceLight = Color(0xFF412B2A)
val inverseOnSurfaceLight = Color(0xFFFFEDEB)
val inversePrimaryLight = Color(0xFFFFB3B1)
val surfaceDimLight = Color(0xFFF6D2D0)
val surfaceBrightLight = Color(0xFFFFF8F7)
val surfaceContainerLowestLight = Color(0xFFFFFFFF)
val surfaceContainerLowLight = Color(0xFFFFF0EF)
val surfaceContainerLight = Color(0xFFFFE9E8)
val surfaceContainerHighLight = Color(0xFFFFE1E0)
val surfaceContainerHighestLight = Color(0xFFFFDAD8)



val primaryDark = Color(0xFFFFB3B1)
val onPrimaryDark = Color(0xFF680012)
val primaryContainerDark = Color(0xFFE90036)
val onPrimaryContainerDark = Color(0xFFFFFFFF)
val secondaryDark = Color(0xFFFFB3B1)
val onSecondaryDark = Color(0xFF680012)
val secondaryContainerDark = Color(0xFF820019)
val onSecondaryContainerDark = Color(0xFFFFC4C2)
val tertiaryDark = Color(0xFFFFB786)
val onTertiaryDark = Color(0xFF502400)
val tertiaryContainerDark = Color(0xFFB95C00)
val onTertiaryContainerDark = Color(0xFFFFFFFF)
val errorDark = Color(0xFFFFB4AB)
val onErrorDark = Color(0xFF690005)
val errorContainerDark = Color(0xFF93000A)
val onErrorContainerDark = Color(0xFFFFDAD6)
val backgroundDark = Color(0xFF200E0E)
val onBackgroundDark = Color(0xFFFFDAD8)
val surfaceDark = Color(0xFF200E0E)
val onSurfaceDark = Color(0xFFFFDAD8)
val surfaceVariantDark = Color(0xFF5F3E3E)
val onSurfaceVariantDark = Color(0xFFE9BCBA)
val outlineDark = Color(0xFFAF8786)
val outlineVariantDark = Color(0xFF5F3E3E)
val scrimDark = Color(0xFF000000)
val inverseSurfaceDark = Color(0xFFFFDAD8)
val inverseOnSurfaceDark = Color(0xFF412B2A)
val inversePrimaryDark = Color(0xFFBF002A)
val surfaceDimDark = Color(0xFF200E0E)
val surfaceBrightDark = Color(0xFF4B3333)
val surfaceContainerLowestDark = Color(0xFF1A0909)
val surfaceContainerLowDark = Color(0xFF2A1616)
val surfaceContainerDark = Color(0xFF2E1A1A)
val surfaceContainerHighDark = Color(0xFF3A2424)
val surfaceContainerHighestDark = Color(0xFF462F2E)






